### PR TITLE
Bootstrap CI

### PR DESCRIPTION
**Pull request by dmsimard**

### CODE REVIEW

**Comment by dmsimard** [comment]
Cleaned up/rebased/squashed commits but noticed Felix's comment in https://github.com/ansible-collections/community.general/issues/1292

He has a point about keeping git history and fixing an issue before moving it here. I'll try and see if we can do that.

**Comment by dmsimard** [comment]
@gundalow @dericcrago I put up a branch that preserves git history from community.general as recommended by Felix: https://github.com/ansible-collections/community.google/tree/bootstrap-with-history

It passes tests (see https://github.com/ansible-collections/community.google/actions/runs/362386888) but it doens't look like we can open a PR from that branch due to diverging git history with the main branch.

Should we then delete the current main branch and then push ``bootstrap-with-history`` to main ?

**Comment by gundalow** [comment]
Sounds like a good plan. Thanks for looking into this.

**Comment by dmsimard** [comment]
@felixfontein pointed out that the original commit timestamps in the branch are wrong -- it might be because of the proposed `` --committer-date-is-author-date`` flag. I'll check and find out.

**Pull request closed without merging**
